spring.application.name=springCRUD

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_crud_db
spring.datasource.username=abhishekyadav
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Initialize schema on startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# CORS Configuration for React Frontend
spring.web.cors.allowed-origin-patterns=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allow-credentials=true
